[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js specific settings
[build.processing]
  skip_processing = true

# Next.js plugin - no inputs needed as we're using the latest version
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle client-side routing - all routes should be rewritten to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Cache settings
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Enable server-side rendering for specific pages
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
